FROM node:alpine as build

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

# Establecer la variable de entorno NODE_OPTIONS
ENV NODE_OPTIONS=--openssl-legacy-provider

RUN yarn build

#---

FROM nginx:alpine

COPY --from=build /app/build/ /var/www
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
